### ISSUE TITLE
Is there option to show only part of day when using hours scale ?

### ISSUE THREAD

**Issue by PrzemekTk** [zunnzunn/vue-ganttastic#118]
I need to show only part of the day on chart  for example  8-15 - is it possible to hide other hours ?

**Comment by zunnzunn** [comment]
Not sure if that is what you mean, but you the `chart-start` prop is a Date-**Time** string value, so you could specify your desired day with 08:00 as the time for `chartStart` and 15:00 for `chartEnd`.
