### ISSUE TITLE
Render row labels in a dedicated column

### ISSUE THREAD

**Issue by LuxiusB44** [zunnzunn/vue-ganttastic#121]
I have a problem with your fantastic Ganttastic library. Specifically, I am having issues with the rows. I want them to look like this (see the first screenshot):
![image](https://github.com/user-attachments/assets/3c7ac9e3-13b1-42c0-a2f8-9e55e61efcda)

But instead, they look like this:
![image](https://github.com/user-attachments/assets/ca9d14f2-1dc8-4ccb-bc99-fc4b43a9e3ef)

I have checked three different projects that have the layout I want, but I cannot see where it has been implemented. If you could help me, it would be greatly appreciated.

Your biggest fan !

**Comment by zunnzunn** [comment]
Hey, @LuxiusB44 ! First of all, thank you for the much appreciated positive feedback!

You can achieve the desired behavior using the props `label-column-title` and `label-column-width` of the `GGanttChart` component. For more infos, check out the [docs](https://zunnzunn.github.io/vue-ganttastic/GGanttChart.html).

When I have time, I will enrich the "Examples" page of the docs with an example using these two props.

**Comment by LuxiusB44** [comment]
Yo @zunnzunn, thanks for your response. However, I'm still having an issue. When I apply your suggestions to my GGantChart component, a new column appears, but the row labels disappear. I have a component called IssueRow that contains g-gantt-row, the problems may be this ? 

After lable-column-title
![Capture d’écran du 2024-08-07 12-31-16](https://github.com/user-attachments/assets/3e1605f2-4315-4efa-bc49-2d4e3c01847e)
Before
![Capture d’écran du 2024-08-07 12-30-48](https://github.com/user-attachments/assets/b2f2c73d-65c5-478e-952d-a4e62decd457)
How i put label into rows : 
![Capture d’écran du 2024-08-07 12-33-40](https://github.com/user-attachments/assets/76a4a7b9-d111-445b-9de8-a385c37de816)
![Capture d’écran du 2024-08-07 12-36-26](https://github.com/user-attachments/assets/8da9c47f-c3e2-4ec5-999a-35dd2c06aff2)

**Comment by tommy3wood** [comment]
Hey @zunnzunn I'm working on an on implementing label-column and the `label-column-width` prop is unresponsive when I try new inputs. I have tried a few different strategies for passing it data and none have stuck. Do you have an example of the proper syntax?
