### ISSUE TITLE
Sticky Time Units and Label Column with max-height/max-width Configurations

### ISSUE THREAD

**Issue by maximilianfixl** [zunnzunn/vue-ganttastic#124]
Referring to the previously discussed "[Horizontal Scrolling](https://github.com/zunnzunn/vue-ganttastic/issues/6)" issue by [Bentipe](https://github.com/Bentipe), I would like to ask about possible future updates:

Are there any plans to introduce features allowing `max-height` and/or `max-width` configurations combined with `overflow: scroll`?

If this cannot be natively implemented via `overflow: scroll`, would it at least be possible to make the `time-units` (also upper) and/or the `label-column` sticky? This would help maintain an overview, especially when dealing with many rows and a broad timeline in the Gantt chart.

I would appreciate any feedback on these ideas and want to take this opportunity to thank you for this great project! 🚀

**Comment by maximilianfixl** [comment]
I was able to solve the issues mentioned by overwriting the CSS classes. You can use `.g-timeaxis` and `.g-label-column` for this. 👍

**Comment by Daukkaaa** [comment]
how did you do it?

**Comment by maximilianfixl** [comment]
It turns out that the structure of the components needs to be reworked in order to make the timeline and label columns sticky. The actual problem isn't the timeline itself - that can be fixed relatively easily with CSS using `overflow` and `sticky`. The real challenge is the label column, which requires restructuring the components to avoid relying on JavaScript for styling (which is highly inefficient, especially for a 3-year timeline displayed by day).

We plan to look into this in the next sprint. We'll provide an update once we have a solution. If you happen to solve it sooner, we'd be very interested in your approach.

**Comment by Daukkaaa** [comment]
i got u))

**Comment by WaledLimbo** [comment]
@maximilianfixl Have fixed the time div ? g-timeaxis ? 

i cant fix it 

how to do ?
