### ISSUE TITLE
Put the rows in the left of the gantt chart

### ISSUE THREAD

**Issue by saadeddineAtif** [zunnzunn/vue-ganttastic#38]
Hi, Can the rows dont be integrated with the gantt chart like in the previous version of V2, Also how can we use tree view?, thank you!

**Comment by LavaYasha** [comment]
same question

> Hi, Can the rows dont be integrated with the gantt chart like in the previous version of V2, Also how can we use tree view?, thank you!

**Comment by InfectoOne** [comment]
Hi! In the current version, it is not possible to separate the row labels from the chart. By having the labels integrated into the chart, you save a lot of space on your screen.
I'd consider merging a pull request which would enable toggling this though.

**Comment by hoctrinh** [comment]
Hello. Has this been updated? I want to put the rows in the left of the gantt chart. Thankyou.

**Comment by zunnzunn** [comment]
The feature has been added in release 2.3.1. See PR #102 .
