### ISSUE TITLE
node_modules/@infectoone/vue-ganttastic/lib/index.d.ts' is not a module

### ISSUE THREAD

**Issue by ginny315** [zunnzunn/vue-ganttastic#63]
hi，I follow the introduction and meet this problem: 
import ganttastic from "@infectoone/vue-ganttastic";"
" File '***/node_modules/@infectoone/vue-ganttastic/lib/index.d.ts' is not a module.
I tried any solutions and cannot resolve, what should I do next?

**Comment by liuliangsir** [comment]
see https://github.com/InfectoOne/vue-ganttastic/issues/32

**Comment by InfectoOne** [comment]
Fixed in v2.1.2. Please install the latest version and tell me if the problem still persists.
