### ISSUE TITLE
GGanttRow - available slot name

### ISSUE THREAD

**Issue by zerexei** [zunnzunn/vue-ganttastic#70]
reference: https://zunnzunn.github.io/vue-ganttastic/GGanttRow.html#slots

The link doesn't show the slots documentation.

What are the available slot name w/ props in GGantRow?
Is it possible to have a progress indicator for GGantRow? (30% bg opacity 1 70% bg opacity .5)
Is it possible to connect two or more GGantRow using arrow based on id?

ps: already reading this: https://github.com/zunnzunn/vue-ganttastic/blob/master/src/components/GGanttRow.vue

**Comment by zunnzunn** [comment]
The slots of GGanttRow are indeed documented, though hyperlinks in the docs do not work in some cases when deployed using GitHub Pages. If that was your issue, simply refresh the page, the links should work then.

![image](https://user-images.githubusercontent.com/28678851/215260664-5253ccb9-9555-4cb2-9c11-51a74393e50f.png)

Regarding the progress indicator and the arrows: the library itself does not support it, but using some HTML/CSS trickery, you should be able to achieve it.
