### ISSUE TITLE
Disable Dragged Feature

### ISSUE THREAD

**Issue by ELFANDI15** [zunnzunn/vue-ganttastic#76]
Hi, is there a way to disable the dragged rows?

**Comment by vitjaz** [comment]
@ELFANDI15 say pls how did you solve your problem?

**Comment by Adesin-fr** [comment]
Maybe too late, but...
in the @drag event, you can override the new position of the dragged bar. 
So, I think you'll just have to return the original bar position so it is not dragged !

**Comment by michaeleichmann** [comment]
I had the same problem and could solve it by having a look at the [TypeScript types of the ganttBarConfig object](https://github.com/zunnzunn/vue-ganttastic/blob/master/src/types.ts#L11C5-L11C13).

Just set `immobile` of your ganttBarConfig to `true`.

@zunnzunn Maybe you could update the docs?
