### ISSUE TITLE
Website is not working

### ISSUE THREAD

**Issue by NathanaelJeremyBleibtreu** [zunnzunn/vue-ganttastic#80]
I, i'm looking for a gantt chart plugin for vue. 

While i was trying to see if vue-ganttastic was a match for my app, i encountered numberless issues on the website.

Can't navigate between page, lots of errors in the console.

I'm using brave in fedora 37.

Cheers

**Comment by koenhendriks** [comment]
Same issues here. Hoping @zunnzunn might notice ;)
