### ISSUE TITLE
can't use "Drag & Drop"

### ISSUE THREAD

**Issue by marnysan111** [zunnzunn/vue-ganttastic#81]
Drop Events are not executed in the following source code.

```
<g-gantt-row v-for="row in GanttData"
                :key="row.label"
                :label="row.label"
                :bars="row.column"
                :highlight-on-hover="true"
                @drop="onDrop($event.e, $event.datetime)"
              />
```

**Comment by marnysan111** [comment]
version: "@infectoone/vue-ganttastic": "^2.1.4",

**Comment by zunnzunn** [comment]
Could you provide some more information? I was not able to reproduce this.

- Could you show how the parent `g-gantt-chart` component looks like?
- How does the data that you pass to the `g-gantt-row` look like?
- Any errors in the console?
- What browser did you use?
