### ISSUE TITLE
I am trying to use slots section in GantChart of ur package and i don't know whether it is working or not. Can u show me an simple example how it works ??

### ISSUE THREAD

**Issue by Khant135** [zunnzunn/vue-ganttastic#88]
![image](https://github.com/zunnzunn/vue-ganttastic/assets/62319034/7c2e542b-17d5-4eb4-bcaa-7f0eb88fc450)

**Comment by zunnzunn** [comment]
```vue
 <g-gantt-chart
    ...
  >
    <template #upper-timeunit="{ label, value }"> Brother </template>
    <template #timeunit="{ label, value }">Broski </template>
    <template #bar-tooltip="{ bar }"> Bruh </template>
    ...
  </g-gantt-chart>
```

Result:  
![image](https://github.com/zunnzunn/vue-ganttastic/assets/28678851/83edd55b-682e-4d04-b2a0-5f2b02d51ffd)

Here's more info on [how scoped slots work in general.](https://vuejs.org/guide/components/slots.html#scoped-slots)
